In [15]:
import jax.numpy as jnp
import numpy as np
import time
import gymnasium as gym
import sys
sys.path.append("..")
import exciting_environments as excenv
from exciting_environments import GymWrapper

In [60]:
pend=excenv.Pendulum(batch_size=5) #,action_constraints={"torque":jnp.array([10,20,30,40,50])}
gym_pend=GymWrapper(env=pend) #,control_state=["theta","omega"]

No chosen control state. Control state is set to [].


In [61]:
gym_pend.reset()

(Array([[-0.2262783 ,  0.69939256],
        [-0.69157934,  0.43567038],
        [ 0.9641855 ,  0.92390746],
        [-0.5804975 ,  0.6503389 ],
        [ 0.10084724, -0.6512029 ]], dtype=float32),
 {})

In [62]:
gym_pend.step(action=jnp.ones(5).reshape(-1,1))

(Array([[-0.22605565,  0.69941056],
        [-0.69144064,  0.43567997],
        [ 0.9644795 ,  0.923963  ],
        [-0.5802905 ,  0.65034145],
        [ 0.10063995, -0.65113765]], dtype=float32),
 Array([[0],
        [0],
        [0],
        [0],
        [0]], dtype=int32),
 Array([[ True],
        [ True],
        [ True],
        [ True],
        [ True]], dtype=bool),
 Array([[False, False],
        [False, False],
        [False, False],
        [False, False],
        [False, False]], dtype=bool))