In [1]:
import jax.numpy as jnp
import numpy as np
import time
import gymnasium as gym
import sys
sys.path.append("..")
import exciting_environments as excenv
from exciting_environments import GymWrapper

In [81]:
pend=excenv.MassSpringDamper(batch_size=5,control_state=["deflection"]) #,action_constraints={"torque":jnp.array([10,20,30,40,50])}
gym_pend=GymWrapper(env=pend)

No chosen control state. Control state is set to ['deflection'].


In [82]:
gym_pend.reset()

(Array([[ 0.41683435, -0.32780242,         nan],
        [-0.6472714 , -0.6467416 ,         nan],
        [-0.03875113, -0.31152892,         nan],
        [ 0.28765512,  0.30928493,         nan],
        [ 0.877296  ,  0.2470727 ,         nan]], dtype=float32),
 {})

In [116]:
gym_pend.step(action=jnp.ones(5).reshape(-1,1))

(Array([[ 0.4154995 , -0.4611838 ,  0.7847402 ],
        [-0.64909244, -0.41772595, -0.89685553],
        [-0.03977548, -0.2903581 , -0.5506203 ],
        [ 0.2885548 ,  0.21722524, -0.37518907],
        [ 0.87765425, -0.04485326,  0.4543922 ]], dtype=float32),
 Array([[3.8636613],
        [3.9386134],
        [3.7390375],
        [3.559444 ],
        [3.8208492]], dtype=float32),
 Array([[False],
        [False],
        [False],
        [False],
        [False]], dtype=bool),
 Array([[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]], dtype=bool))