In [98]:
import jax.numpy as jnp
import jax
import numpy as np
import time
import gymnasium as gym
import sys
sys.path.append("..")
import exciting_environments as excenv
from exciting_environments import GymWrapper
import jax_dataclasses as jdc

In [99]:
pend=excenv.Pendulum(batch_size=5,action_constraints={"torque":jnp.array([10,20,30,40,50])}) #
gym_pend=GymWrapper(env=pend,control_state=["theta"]) #,control_state=["theta","omega"]

In [100]:
pend.obs_description

array(['theta', 'omega', 'theta_ref'], dtype='<U9')

In [115]:
key=jax.vmap(jax.random.PRNGKey)(np.random.randint(0, 2**31, size=(pend.batch_size,)))
obs,_=gym_pend.reset(key)

In [120]:
gym_pend.step(action=jnp.ones(5).reshape(-1,1))

(Array([[ 0.8403935 , -0.61675113,  0.09291338],
        [-0.6662587 ,  0.7986739 ,  0.58666635],
        [ 0.28154412,  0.28632787, -0.3777313 ],
        [-0.19206604, -0.20114493, -0.41738772],
        [ 0.50969005, -0.5957422 ,  0.14515686]], dtype=float32),
 Array([[-3.4029741],
        [-3.4011583],
        [-2.9595153],
        [-0.4805015],
        [-1.1742989]], dtype=float32),
 Array([[False],
        [False],
        [False],
        [False],
        [False]], dtype=bool),
 Array([[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]], dtype=bool))