In [1]:
import jax.numpy as jnp
import numpy as np
import time
import gymnasium as gym
import sys
sys.path.append("..")
import exciting_environments as excenv
from exciting_environments import GymWrapper

In [7]:
pend=excenv.FluidTank(batch_size=5) #,action_constraints={"torque":jnp.array([10,20,30,40,50])}
gym_pend=GymWrapper(env=pend)

In [8]:
gym_pend.reset()

(Array([[0.],
        [0.],
        [0.],
        [0.],
        [0.]], dtype=float32, weak_type=True),
 {})

In [9]:
gym_pend.step(action=jnp.ones(5).reshape(-1,1))

(Array([[2.0742416e-05],
        [2.0742416e-05],
        [2.0742416e-05],
        [2.0742416e-05],
        [2.0742416e-05]], dtype=float32),
 Array([[0],
        [0],
        [0],
        [0],
        [0]], dtype=int32),
 Array([[False],
        [False],
        [False],
        [False],
        [False]], dtype=bool),
 Array([[0],
        [0],
        [0],
        [0],
        [0]], dtype=int32))