In [1]:
import jax.numpy as jnp
import numpy as np
import time
import gymnasium as gym
import sys
sys.path.append("..")
import exciting_environments as excenv
from exciting_environments import GymWrapper
from jax.tree_util import tree_flatten, tree_unflatten, tree_structure

In [2]:
pend=excenv.CartPole(batch_size=5,action_constraints={"force":jnp.array([10,20,30,40,50])})
gym_pend=GymWrapper(env=pend)

In [3]:
jnp.array(tree_flatten(pend.env_properties.action_constraints)[0]).T

Array([[10],
       [20],
       [30],
       [40],
       [50]], dtype=int32)

In [4]:
jnp.array(list(
                pend.env_properties.action_constraints.__dict__.values()
            )).T

Array([[10],
       [20],
       [30],
       [40],
       [50]], dtype=int32)

In [5]:
pend.init_states()

CoreEnvironment.States(physical_states=CartPole.PhysicalStates(deflection=Array([0., 0., 0., 0., 0.], dtype=float32), velocity=Array([0., 0., 0., 0., 0.], dtype=float32), theta=Array([3.1415927, 3.1415927, 3.1415927, 3.1415927, 3.1415927],      dtype=float32, weak_type=True), omega=Array([0., 0., 0., 0., 0.], dtype=float32)), PRNGKey=None, optional=None)

In [6]:
gym_pend.reset()

(Array([[0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]], dtype=float32),
 {})

In [20]:
gym_pend.step(action=jnp.ones(5).reshape(-1,1))

(Array([[ 7.2799963e-07,  1.1199986e-03, -9.9999815e-01,  8.3999726e-04],
        [ 1.4559992e-06,  2.2399973e-03, -9.9999624e-01,  1.6799942e-03],
        [ 2.1839985e-06,  3.3599958e-03, -9.9999470e-01,  2.5199919e-03],
        [ 2.9119985e-06,  4.4799945e-03, -9.9999309e-01,  3.3599895e-03],
        [ 3.6399983e-06,  5.5999937e-03, -9.9999124e-01,  4.1999868e-03]],      dtype=float32),
 Array([[1.0999964],
        [1.0999932],
        [1.0999912],
        [1.0999893],
        [1.0999874]], dtype=float32),
 Array([[False],
        [False],
        [False],
        [False],
        [False]], dtype=bool),
 Array([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]], dtype=bool),
 {})

### Simulate Ahead

In [21]:
pend=excenv.Pendulum(batch_size=5,action_constraints={"torque":20})
init_obs,init_states=pend.reset()

In [22]:
actions=jnp.full((5,6),20)

In [23]:
obs=pend.vmap_simulate_ahead(init_states=init_states,actions=actions,init_obs=init_obs)

AttributeError: 'Pendulum' object has no attribute 'vmap_simulate_ahead'

In [ ]:
obs

Array([[[ 1.00000000e+00,  0.00000000e+00],
        [ 1.00000000e+00,  0.00000000e+00],
        [ 1.00000000e+00,  0.00000000e+00],
        [ 1.00000000e+00,  0.00000000e+00],
        [ 1.00000000e+00,  0.00000000e+00]],

       [[-1.00000000e+00,  4.99999987e-05],
        [-1.00000000e+00,  4.99999987e-05],
        [-1.00000000e+00,  4.99999987e-05],
        [-1.00000000e+00,  4.99999987e-05],
        [-1.00000000e+00,  4.99999987e-05]],

       [[-1.00000000e+00,  1.00000005e-04],
        [-1.00000000e+00,  1.00000005e-04],
        [-1.00000000e+00,  1.00000005e-04],
        [-1.00000000e+00,  1.00000005e-04],
        [-1.00000000e+00,  1.00000005e-04]],

       [[-1.00000000e+00,  1.50000022e-04],
        [-1.00000000e+00,  1.50000022e-04],
        [-1.00000000e+00,  1.50000022e-04],
        [-1.00000000e+00,  1.50000022e-04],
        [-1.00000000e+00,  1.50000022e-04]],

       [[-9.99999940e-01,  2.00000009e-04],
        [-9.99999940e-01,  2.00000009e-04],
        [-9.99999940e-01