In [1]:
import jax.numpy as jnp
import numpy as np
import time
import gymnasium as gym
import sys
sys.path.append("..")
import exciting_environments as excenv
from exciting_environments import GymWrapper

In [6]:
pend=excenv.Pendulum(batch_size=5,action_constraints={"force":20})
gym_pend=GymWrapper(env=pend)

In [7]:
pend.init_states()

CoreEnvironment.States(physical_states=MassSpringDamper.PhysicalStates(deflection=Array([0., 0., 0., 0., 0.], dtype=float32), velocity=Array([0., 0., 0., 0., 0.], dtype=float32)), PRNGKey=None, optional=None)

In [8]:
gym_pend.reset()

(Array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=float32),
 {})

In [45]:
gym_pend.step(action=jnp.ones(5).reshape(-1,1))

(Array([[1.3303153e-05, 7.3851445e-03],
        [1.3303153e-05, 7.3851445e-03],
        [1.3303153e-05, 7.3851445e-03],
        [1.3303153e-05, 7.3851445e-03],
        [1.3303153e-05, 7.3851445e-03]], dtype=float32),
 Array([[0.10000546],
        [0.10000546],
        [0.10000546],
        [0.10000546],
        [0.10000546]], dtype=float32),
 Array([[False],
        [False],
        [False],
        [False],
        [False]], dtype=bool),
 Array([[False, False],
        [False, False],
        [False, False],
        [False, False],
        [False, False]], dtype=bool),
 {})